const char *VI_CONF = 
"s vi;"
"s global;"
"b Escape g vi;"
"b A-Escape g vi;"
"b C-c g vi;"
"b C-q signal int;"
"s vi;"
"r;"
"i char;"
"b C-c i;"
"b j k Down;"
"b k k Up;"
"b h k Left;"
"b l k Right;"
"b C-d k PageDown;"
"b C-u k PageUp;"
"b 0 k Home;"
"b $ k End;"
"b g k -r 4 PageUp;"
"b G k -r 4 PageDown;"
"b w k -r 6 Right;"
"b e k -r 4 Right;"
"b b k -r 4 Left;"
"b B k -r 8 Left;"
"b x k Delete;"
"b d k Delete;"
"b D k Delete;"
"b i g global;"
"b a k Right \\; g global;"
"b I k C-a \\; g global;"
"b A k C-e \\; g global;"
"b o k Down \\; g global;"
"b O k Up \\; g global;"
;
