const char *VI_CONF = 
"mo global;"
"b Escape go vi;"
"b A-Escape go vi;"
"b C-c go vi;"
"b C-q signal INT;"
"mo vi;"
"re on;"
"ig char;"
"b C-c ig;"
"b j ke Down;"
"b k ke Up;"
"b h ke Left;"
"b l ke Right;"
"b C-d ke PageDown;"
"b C-u ke PageUp;"
"b 0 ke Home;"
"b $ ke End;"
"b g ke -r 4 PageUp;"
"b G ke -r 4 PageDown;"
"b w ke -r 6 Right;"
"b e ke -r 4 Right;"
"b b ke -r 4 Left;"
"b B ke -r 8 Left;"
"b x ke Delete;"
"b d ke Delete;"
"b D ke -r 80 Delete;"
"b C ke -r 80 Delete \\; go global;"
"b i go global;"
"b a ke Right \\; go global;"
"b I ke C-a \\; go global;"
"b A ke C-e \\; go global;"
"b o ke Down \\; go global;"
"b O ke Up \\; go global;"
;
